'use strict';

window.TOUCHSCALE_SAMPLES = [
  {
    "id": "pipette-tip",
    "name": "Attaching a pipette tip",
    "category": "Laboratory",
    "label": "Fine manipulation",
    "description": "Attach a 1 mL pipette tip vertically, then return the pipette to its stand.",
    "duration": 20.0,
    "image": "assets/images/human/pipette-tip.webp",
    "poster": "assets/images/human/pipette-tip-sensors.webp",
    "video": "assets/videos/human/pipette-tip-head.mp4",
    "sensors": "assets/videos/human/pipette-tip-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "sponge",
    "name": "Squeezing a wet sponge",
    "category": "Kitchen",
    "label": "Deformable contact",
    "description": "Squeeze a wet sponge over a bowl, revealing changing contact across the fingers and palm.",
    "duration": 15.53,
    "image": "assets/images/human/sponge.webp",
    "poster": "assets/images/human/sponge-sensors.webp",
    "video": "assets/videos/human/sponge-head.mp4",
    "sensors": "assets/videos/human/sponge-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "wrench",
    "name": "Tightening a nut",
    "category": "Workbench",
    "label": "Tool use",
    "description": "Use an adjustable wrench to tighten a large hex nut while stabilizing the workpiece.",
    "duration": 24.33,
    "image": "assets/images/human/wrench.webp",
    "poster": "assets/images/human/wrench-sensors.webp",
    "video": "assets/videos/human/wrench-head.mp4",
    "sensors": "assets/videos/human/wrench-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "gauze",
    "name": "Unfolding gauze",
    "category": "Medical / First Aid",
    "label": "Soft materials",
    "description": "Unfold a large piece of gauze and spread it flat with both hands.",
    "duration": 23.67,
    "image": "assets/images/human/gauze.webp",
    "poster": "assets/images/human/gauze-sensors.webp",
    "video": "assets/videos/human/gauze-head.mp4",
    "sensors": "assets/videos/human/gauze-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "tube-sort",
    "name": "Sorting centrifuge tubes",
    "category": "Laboratory",
    "label": "Object sorting",
    "description": "Separate small and large centrifuge tubes into their designated areas.",
    "duration": 25.667,
    "image": "assets/images/human/tube-sort.webp",
    "video": "assets/videos/human/tube-sort-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/tube-sort-sensors.webp",
    "sensors": "assets/videos/human/tube-sort-sensors.mp4"
  },
  {
    "id": "pour-cup",
    "name": "Pouring water",
    "category": "Kitchen",
    "label": "Liquid transfer",
    "description": "Pour water from a wide-mouth bottle into a plastic cup.",
    "duration": 23.07,
    "image": "assets/images/human/pour-cup.webp",
    "poster": "assets/images/human/pour-cup-sensors.webp",
    "video": "assets/videos/human/pour-cup-head.mp4",
    "sensors": "assets/videos/human/pour-cup-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "dowel-hammer",
    "name": "Tapping a wooden dowel",
    "category": "Workbench",
    "label": "Tool contact",
    "description": "Tap a wooden dowel with a rubber mallet until it sits flush with the wood.",
    "duration": 21.6,
    "image": "assets/images/human/dowel-hammer.webp",
    "video": "assets/videos/human/dowel-hammer-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/dowel-hammer-sensors.webp",
    "sensors": "assets/videos/human/dowel-hammer-sensors.mp4"
  },
  {
    "id": "usb",
    "name": "Connecting a cable",
    "category": "Office",
    "label": "Precise insertion",
    "description": "Align a cable connector with a socket and insert it while holding the power strip steady.",
    "duration": 15.8,
    "image": "assets/images/human/usb.webp",
    "poster": "assets/images/human/usb-sensors.webp",
    "video": "assets/videos/human/usb-head.mp4",
    "sensors": "assets/videos/human/usb-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "powder-transfer",
    "name": "Scooping powder into a beaker",
    "category": "Laboratory",
    "label": "Tool coordination",
    "description": "Use a laboratory spoon to transfer powder into a beaker.",
    "duration": 14.067,
    "image": "assets/images/human/powder-transfer.webp",
    "video": "assets/videos/human/powder-transfer-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/powder-transfer-sensors.webp",
    "sensors": "assets/videos/human/powder-transfer-sensors.mp4"
  },
  {
    "id": "bottle",
    "name": "Closing a bottle",
    "category": "Kitchen",
    "label": "Grasping & rotation",
    "description": "Hold a small bottle steady while twisting its screw cap closed.",
    "duration": 14.93,
    "image": "assets/images/human/bottle.webp",
    "poster": "assets/images/human/bottle-sensors.webp",
    "video": "assets/videos/human/bottle-head.mp4",
    "sensors": "assets/videos/human/bottle-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "tape-retract",
    "name": "Retracting a tape measure",
    "category": "Workbench",
    "label": "Controlled motion",
    "description": "Release the lock and slowly retract a tape measure.",
    "duration": 22.867,
    "image": "assets/images/human/tape-retract.webp",
    "video": "assets/videos/human/tape-retract-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/tape-retract-sensors.webp",
    "sensors": "assets/videos/human/tape-retract-sensors.mp4"
  },
  {
    "id": "book-pack",
    "name": "Packing a book",
    "category": "Packing / Shipping",
    "label": "Bimanual handling",
    "description": "Place a hardcover book into an open bubble mailer.",
    "duration": 22.667,
    "image": "assets/images/human/book-pack.webp",
    "video": "assets/videos/human/book-pack-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/book-pack-sensors.webp",
    "sensors": "assets/videos/human/book-pack-sensors.mp4"
  },
  {
    "id": "test-strip",
    "name": "Dipping a test strip",
    "category": "Laboratory",
    "label": "Precise tool use",
    "description": "Hold a test strip with tweezers and dip it into liquid.",
    "duration": 17.933,
    "image": "assets/images/human/test-strip.webp",
    "video": "assets/videos/human/test-strip-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/test-strip-sensors.webp",
    "sensors": "assets/videos/human/test-strip-sensors.mp4"
  },
  {
    "id": "wipe",
    "name": "Wiping a countertop",
    "category": "Kitchen",
    "label": "Surface contact",
    "description": "Wipe the countertop beside a cutting board with a cloth.",
    "duration": 25.87,
    "image": "assets/images/human/wipe.webp",
    "poster": "assets/images/human/wipe-sensors.webp",
    "video": "assets/videos/human/wipe-head.mp4",
    "sensors": "assets/videos/human/wipe-sensors.mp4",
    "width": 512,
    "height": 340
  },
  {
    "id": "bulb-install",
    "name": "Fitting a light bulb",
    "category": "Workbench",
    "label": "Threaded assembly",
    "description": "Rotate an E27 light bulb into its matching holder.",
    "duration": 17.333,
    "image": "assets/images/human/bulb-install.webp",
    "video": "assets/videos/human/bulb-install-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/bulb-install-sensors.webp",
    "sensors": "assets/videos/human/bulb-install-sensors.mp4"
  },
  {
    "id": "socks-roll",
    "name": "Rolling socks",
    "category": "Bedroom",
    "label": "Cloth handling",
    "description": "Roll folded socks into a compact bundle.",
    "duration": 21.8,
    "image": "assets/images/human/socks-roll.webp",
    "video": "assets/videos/human/socks-roll-head.mp4",
    "width": 512,
    "height": 340,
    "poster": "assets/images/human/socks-roll-sensors.webp",
    "sensors": "assets/videos/human/socks-roll-sensors.mp4"
  }
];
